# Generated by Django 3.0.5 on 2020-12-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.IntegerField()),
                ('max_mm', models.IntegerField()),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblDayTanks',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblEngines',
            },
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('cap_kw', models.IntegerField()),
            ],
            options={
                'db_table': 'tblGenerators',
            },
        ),
        migrations.CreateModel(
            name='Genset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(db_index=True, unique=True)),
                ('operational', models.BooleanField(default=True)),
                ('cap_kw', models.IntegerField()),
                ('daytank', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cps.DayTank')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.Engine')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.Generator')),
            ],
            options={
                'db_table': 'tblGensets',
            },
        ),
        migrations.CreateModel(
            name='StorageTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(db_index=True, unique=True)),
                ('max_mm', models.IntegerField()),
            ],
            options={
                'db_table': 'tblStorageTanks',
            },
        ),
        migrations.CreateModel(
            name='StorageTankRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('record_time', models.TimeField()),
                ('details', models.CharField(max_length=255)),
                ('sounding', models.IntegerField()),
                ('liters', models.IntegerField()),
                ('diff', models.IntegerField()),
                ('storage_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.StorageTank')),
            ],
            options={
                'db_table': 'tblStorageTankRecords',
            },
        ),
        migrations.CreateModel(
            name='RunRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('record_time', models.TimeField()),
                ('action', models.CharField(choices=[('R', 'Start'), ('S', 'Stop')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Genset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.Genset')),
            ],
            options={
                'db_table': 'tblRunRecords',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('record_time', models.TimeField()),
                ('no', models.IntegerField(db_index=True)),
                ('reading', models.IntegerField()),
                ('ecc', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Genset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.Genset')),
            ],
            options={
                'db_table': 'tblProductionRecords',
            },
        ),
        migrations.CreateModel(
            name='DayTankRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('record_time', models.TimeField()),
                ('no', models.IntegerField(db_index=True)),
                ('is_daily_final', models.BooleanField(default=False)),
                ('initial_mm', models.IntegerField()),
                ('final_mm', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Genset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.Genset')),
                ('daytank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.DayTank')),
                ('storage_tank_record', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cps.StorageTankRecord')),
            ],
            options={
                'db_table': 'tblDayTankRecords',
            },
        ),
    ]
