# Generated by Django 3.0.5 on 2020-12-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytank',
            name='multiplier',
            field=models.FloatField(),
        ),
    ]
