# Generated by Django 3.0.5 on 2020-12-20 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0002_auto_20201219_2345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genset',
            unique_together={('engine', 'generator')},
        ),
    ]
