# Generated by Django 3.0.5 on 2020-11-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0003_auto_20201130_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='genset',
            name='updated_at',
        ),
    ]
