# Generated by Django 3.0.5 on 2020-11-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0004_auto_20201130_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('record_time', models.TimeField()),
                ('action', models.CharField(choices=[('START', 'Start'), ('STOP', 'Stop')], max_length=5)),
                ('genset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.Genset')),
            ],
        ),
    ]
