# Generated by Django 3.0.5 on 2020-12-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0005_auto_20201221_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagetankrecord',
            name='shift',
            field=models.CharField(default='X', max_length=1),
            preserve_default=False,
        ),
    ]
