# Generated by Django 3.0.5 on 2020-11-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0008_auto_20201201_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytankinfo',
            name='genset_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cps.Genset'),
        ),
        migrations.AlterField(
            model_name='runrecord',
            name='genset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.Genset'),
        ),
    ]
